# everforest Colours
# background_color "#232a2e"
# current_line_color '#2d353b'
# foreground_color '#343f44'
# comment_color '#475258'
# cyan "#83c092"
# green "#a7c080"
# orange "#e69875"
# pink '#ff79c6'
# purple "#d699b6"
# red "#e67e80"
# yellow "#dbbc7f"

#fg = "#d3c6aa",
#red = "#e67e80",
#orange = "#e69875",
#yellow = "#dbbc7f",
#green = "#a7c080",
#aqua = "#83c092",
#blue = "#7fbbb3",
#purple = "#d699b6",
#grey0 = "#7a8478",
#grey1 = "#859289",
#grey2 = "#9da9a0",
#statusline1 = "#a7c080",
#statusline2 = "#d3c6aa",
#statusline3 = "#e67e80",

#set -g status-justify left
#
## pane border
#set -g pane-border-style fg='#475258'
#set -g pane-active-border-style fg='#7a8478'
#
## message text
#set -g message-style bg='#2d353b',fg='#d3c6aa'
#
#set -g status-style bg='#2d353b',fg="#475258"
#set -g status-interval 1
#
## status left
## are we controlling tmux or the content of the panes?
#set -g status-left '#[bg=#a7c080]#[fg=#282a36]#{?client_prefix,#[bg=#d3c6aa],} TMUX'
#
## are we zoomed into a pane?
#set -ga status-left '#[bg="#d699b6"]#[fg=#ff79c6] #{?window_zoomed_flag, ↕  ,   }'
#
## window status
#set-window-option -g window-status-style fg='#d3c6aa',bg='#343f44'
#
#set -g window-status-current-format "#[g=#d3c6aa]#[bg=#343f44] #[g=#d3c6aa]#[bg=#343f44] #I #W #[fg=#d3c6aa]#[bg=#44475a]"
#set -g window-status-format "#[fg=#f8f8f2]#[bg=#475258]#I #W #[fg=#44475a]"
#
## status right -- Powershell cuts off last few chars
## set -g status-right '#[fg=#282a36,bg=#a7c080]#{?client_prefix,#[bg=#d3c6aa],} #{pane_current_path} |  | ...'


